### ISSUE TITLE
Clean all tables regardless of schema

### ISSUE THREAD

**Issue by adelinmaubray** [cronn/test-utils#2]
Hello,

I would like to use h2Util.resetDatabase(); but my database is using a default schema name.
Therefore, when the library tries to do any request, it throws an error because the table is not found.

Instead of 
`SELECT COUNT(*) FROM TABLE_NAME`
something like
`SELECT COUNT(*) FROM SCHEMA_NAME.TABLE_NAME`
should be great

Kindest regards

**Comment by adelinmaubray** [comment]
Hi rpost,
To be honest I didn't think about the possibility to clean table regardless of schema.  But indeed it seems the best solution 😁
I will rename the issue title then

**Comment by rpost** [comment]
Implemented and released as 0.3.0
